server:
  port: 8081  

database:
  host: 127.0.0.1
  port: 3306
  user: root      
  password: root  
  dbname: order_payment  

redis:
  host: 127.0.0.1
  port: "6379"
  password: ""
  DB: 0
  PoolSize: 10

rabbitmq:
  host: 127.0.0.1
  port: 5672                
  user: guest               
  password: guest        
  vhost: "/"   

jwt:
  secret: "my-secret-key"         